### ISSUE TITLE
'SimpleT5' object has no attribute 'device'

### ISSUE THREAD

**Issue by athack** [Shivanandroy/simpleT5#20]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/t5/lib/python3.8/site-packages/simplet5/simplet5.py", line 442, in predict
    input_ids = input_ids.to(self.device)
AttributeError: 'SimpleT5' object has no attribute 'device'`

**Comment by mahowak** [comment]
I am having the same issue. Is there a fix for this?

**Comment by pashok3d** [comment]
You need to add `use_gpu` argument in `predict` function, then add the same [code block](https://github.com/Shivanandroy/simpleT5/blob/94ad898c428f48d13cb40d0acd237198475e80b3/simplet5/simplet5.py#L394-L400) as in `load_model` to set `self.device` attribute properly. @Shivanandroy

**Comment by savasy** [comment]
Or Simple
``
import torch

model.device=  torch.device("cpu")
``

**Comment by ke-lara** [comment]
> `Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/home/user/.virtualenvs/t5/lib/python3.8/site-packages/simplet5/simplet5.py", line 442, in predict input_ids = input_ids.to(self.device) AttributeError: 'SimpleT5' object has no attribute 'device'`

Did you 'load_model' before 'predict'?
